OG\InversaBundle\Entity\AgendaItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: { limit: 3, message: "Mind. {{ limit }} Zeichen erwartet" }
OG\InversaBundle\Entity\CdItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: { limit: 3, message: "Mind. {{ limit }} Zeichen erwartet" }
OG\InversaBundle\Entity\Document:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Dokument Namen eingeben" }
            - MinLength: { limit: 3, message: "Mind. {{ limit }} Zeichen erwartet" }
        file:
            - NotBlank: { message: "Bitte eine Datei angeben" }
            - MinLength: { limit: 3, message: "Mind. {{ limit }} Zeichen erwartet" } 
OG\InversaBundle\Entity\GalleryItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: { limit: 3, message: "Mind. {{ limit }} Zeichen erwartet" }
OG\InversaBundle\Entity\Image:
    getters:
        valid:
            - "True": { message: "Bild Angaben sind unvollständig" }
OG\InversaBundle\Entity\Document:
    properties:            
        file:
            - File:
                maxSize: 3M
                maxSizeMessage: Datei ist zu gross ({{ size }}). Maximalgrösse ist {{ limit }}
                mimeTypes: [application/pdf, application/x-pdf, text/plain, text/xml, application/msword]
                mimeTypesMessage: PDF, Word oder Text Datei
                uploadErrorMessage: Die Datei konnte nicht hochgeladen werden
OG\InversaBundle\Entity\Image:
    properties:            
        file:
            - Image:
                maxSize: 2M
                maxSizeMessage: Datei ist zu gross ({{ size }}). Maximalgrösse ist {{ limit }}
                mimeTypes: [image/png, image/jpeg, image/gif]
                mimeTypesMessage: Bild Datei (PNG, JPEG, GIF)
                uploadErrorMessage: Die Datei konnte nicht hochgeladen werden
OG\InversaBundle\Entity\MediaItem:
    properties:            
        mediafile:
            - File:
                maxSize: 30M
                maxSizeMessage: Datei ist zu gross ({{ size }}). Maximalgrösse ist {{ limit }}
                mimeTypes: [audio/mpeg, audio/wav, video/mp4, video/avi]
                mimeTypesMessage: Audio (MP3/WAV) oder Video (MP4/AVI) Datei
                uploadErrorMessage: Die Datei konnte nicht hochgeladen werden 
OG\InversaBundle\Entity\InversaUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: username, message: "Dieser Benutzername wird bereits verwendet" }
    properties:
        username:
            - NotBlank: { message: "Bitte einen gültigen Benutzernamen eingeben [mind. 5 Zeichen, eindeutig]" }
            - MinLength: { limit: 5, message: "Mind. {{ limit }} Zeichen erwartet" }
        newpassword:
            - MinLength: { limit: 5, message: "Mind. {{ limit }} Zeichen erwartet" }
    getters:
        repeatPasswordOk:
            - "True": { message: "Passwörter stimmen nicht überein" }
        oldPasswordOk:
            - "True": { message: "Altes Passwort ist nicht korrekt" }                        