OG\InversaBundle\Entity\AgendaItem:
    properties:
        name:
            - NotBlank: ~
            - MinLength: 3
OG\InversaBundle\Entity\Document:
    properties:            
        file:
            - File:
                maxSize: 3072k
                mimeTypes: [application/pdf, application/x-pdf, text/plain, text/xml, application/msword]
                mimeTypesMessage: PDF, Word oder Text Datei (<3MB)
OG\InversaBundle\Entity\Image:
    properties:            
        file:
            - Image:
                maxSize: 2048k
                mimeTypes: [image/png, image/jpeg, image/gif]
                mimeTypesMessage: Bild Datei (PNG, JPEG, GIF, <2MB)
OG\InversaBundle\Entity\MediaItem:
    properties:            
        file:
            - MediaFile:
                maxSize: 15360k
                mimeTypes: [audio/mpeg, video/avi, video/mpeg]
                mimeTypesMessage: Audio oder Video Datei (MP3, AVI, MPEG, <15MB)