OG\InversaBundle\Entity\AgendaItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: 3
OG\InversaBundle\Entity\CdItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: 3
OG\InversaBundle\Entity\Document:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Dokument Namen eingeben" }
            - MinLength: 3    
        file:
            - NotBlank: { message: "Bitte eine Datei angeben" }
            - MinLength: 3 
OG\InversaBundle\Entity\GalleryItem:
    properties:
        name:
            - NotBlank: { message: "Bitte einen gültigen Namen eingeben" }
            - MinLength: 3
OG\InversaBundle\Entity\Image:
    getters:
        valid:
            - "True": { message: "Bild Angaben sind unvollständig" }
OG\InversaBundle\Entity\Document:
    properties:            
        file:
            - File:
                maxSize: 3072k
                mimeTypes: [application/pdf, application/x-pdf, text/plain, text/xml, application/msword]
                mimeTypesMessage: PDF, Word oder Text Datei (<3MB)
OG\InversaBundle\Entity\Image:
    properties:            
        file:
            - Image:
                maxSize: 2048k
                mimeTypes: [image/png, image/jpeg, image/gif]
                mimeTypesMessage: Bild Datei (PNG, JPEG, GIF, <2MB)
OG\InversaBundle\Entity\MediaItem:
    properties:            
        mediafile:
            - File:
                maxSize: 15360k
                mimeTypes: [audio/mpeg, audio/wav, video/avi, video/mpeg]
                mimeTypesMessage: Audio oder Video Datei (MP3/WAV, AVI/MPEG, <15MB)