CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, projectitem_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, doctype VARCHAR(32) DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, INDEX IDX_D8698A76FCF85E97 (projectitem_id), PRIMARY KEY(id)) ENGINE = InnoDB;
ALTER TABLE document ADD CONSTRAINT FK_D8698A76FCF85E97 FOREIGN KEY (projectitem_id) REFERENCES projectitem(id);
ALTER TABLE galleryitem CHANGE description description LONGTEXT DEFAULT NULL;
ALTER TABLE mediaitem ADD isactive TINYINT(1) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL;
ALTER TABLE pressitem ADD published DATETIME NOT NULL, ADD isactive TINYINT(1) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL;
ALTER TABLE projectitem ADD isactive TINYINT(1) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL;
ALTER TABLE weburl DROP FOREIGN KEY FK_6C2FC7D3FCBB33CA;
DROP INDEX IDX_6C2FC7D3FCBB33CA ON weburl;
ALTER TABLE weburl CHANGE agendaitem_id projectitem_id INT DEFAULT NULL;
ALTER TABLE weburl ADD CONSTRAINT FK_6C2FC7D3FCF85E97 FOREIGN KEY (projectitem_id) REFERENCES projectitem(id);
CREATE INDEX IDX_6C2FC7D3FCF85E97 ON weburl (projectitem_id)
