<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('SyrinxCalendar', 'doctrine');

/**
 * BaseSyrinxCalendar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property date $date
 * @property string $time
 * @property integer $duration
 * @property string $description
 * @property string $participants
 * @property string $venue
 * @property string $map
 * @property string $image
 * @property string $file1
 * @property string $file1name
 * @property string $file2
 * @property string $file2name
 * @property string $file3
 * @property string $file3name
 * @property string $file4
 * @property string $file4name
 * @property string $link1
 * @property string $link1name
 * @property string $link2
 * @property string $link2name
 * @property boolean $is_published
 * 
 * @method string         getTitle()        Returns the current record's "title" value
 * @method date           getDate()         Returns the current record's "date" value
 * @method string         getTime()         Returns the current record's "time" value
 * @method integer        getDuration()     Returns the current record's "duration" value
 * @method string         getDescription()  Returns the current record's "description" value
 * @method string         getParticipants() Returns the current record's "participants" value
 * @method string         getVenue()        Returns the current record's "venue" value
 * @method string         getMap()          Returns the current record's "map" value
 * @method string         getImage()        Returns the current record's "image" value
 * @method string         getFile1()        Returns the current record's "file1" value
 * @method string         getFile1name()    Returns the current record's "file1name" value
 * @method string         getFile2()        Returns the current record's "file2" value
 * @method string         getFile2name()    Returns the current record's "file2name" value
 * @method string         getFile3()        Returns the current record's "file3" value
 * @method string         getFile3name()    Returns the current record's "file3name" value
 * @method string         getFile4()        Returns the current record's "file4" value
 * @method string         getFile4name()    Returns the current record's "file4name" value
 * @method string         getLink1()        Returns the current record's "link1" value
 * @method string         getLink1name()    Returns the current record's "link1name" value
 * @method string         getLink2()        Returns the current record's "link2" value
 * @method string         getLink2name()    Returns the current record's "link2name" value
 * @method boolean        getIsPublished()  Returns the current record's "is_published" value
 * @method SyrinxCalendar setTitle()        Sets the current record's "title" value
 * @method SyrinxCalendar setDate()         Sets the current record's "date" value
 * @method SyrinxCalendar setTime()         Sets the current record's "time" value
 * @method SyrinxCalendar setDuration()     Sets the current record's "duration" value
 * @method SyrinxCalendar setDescription()  Sets the current record's "description" value
 * @method SyrinxCalendar setParticipants() Sets the current record's "participants" value
 * @method SyrinxCalendar setVenue()        Sets the current record's "venue" value
 * @method SyrinxCalendar setMap()          Sets the current record's "map" value
 * @method SyrinxCalendar setImage()        Sets the current record's "image" value
 * @method SyrinxCalendar setFile1()        Sets the current record's "file1" value
 * @method SyrinxCalendar setFile1name()    Sets the current record's "file1name" value
 * @method SyrinxCalendar setFile2()        Sets the current record's "file2" value
 * @method SyrinxCalendar setFile2name()    Sets the current record's "file2name" value
 * @method SyrinxCalendar setFile3()        Sets the current record's "file3" value
 * @method SyrinxCalendar setFile3name()    Sets the current record's "file3name" value
 * @method SyrinxCalendar setFile4()        Sets the current record's "file4" value
 * @method SyrinxCalendar setFile4name()    Sets the current record's "file4name" value
 * @method SyrinxCalendar setLink1()        Sets the current record's "link1" value
 * @method SyrinxCalendar setLink1name()    Sets the current record's "link1name" value
 * @method SyrinxCalendar setLink2()        Sets the current record's "link2" value
 * @method SyrinxCalendar setLink2name()    Sets the current record's "link2name" value
 * @method SyrinxCalendar setIsPublished()  Sets the current record's "is_published" value
 * 
 * @package    syrinx
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSyrinxCalendar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('syrinx_calendar');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('date', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('time', 'string', 256, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 256,
             ));
        $this->hasColumn('duration', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => false,
             'length' => 8,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('participants', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('venue', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('map', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('image', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file1', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file1name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file2', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file2name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file3', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file3name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file4', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('file4name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('link1', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('link1name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('link2', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('link2name', 'string', 1024, array(
             'type' => 'string',
             'length' => 1024,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}