OGInversaBundle:
    resource: "@OGInversaBundle/Controller"
    type:     annotation

_imagine:
    resource: .
    type:     imagine
        
# import routes from a controller class
# admin:
#     resource: "@OGInversaBundle/Controller/AdminController.php"
#     type:     annotation
#     
# agenda:
#     resource: "@OGInversaBundle/Controller/AgendaItemController.php"
#     type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
