#OGInversaBundle:
#    resource: "@OGInversaBundle/Resources/config/routing.yml"
#    prefix:   /
    
content:
    resource: "@OGInversaBundle/Controller/ContentController.php"
    prefix:   /
    type:     annotation
    
# import routes from a controller class
admin:
    resource: "@OGInversaBundle/Controller/AdminController.php"
    type:     annotation

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
