generator:
  class: sfDoctrineGenerator
  param:
    model_class:           SyrinxProject
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          syrinx_project
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        title:        { label: Titel }
        description:  { label: Beschreibung }
        image:        { label: Bild }
        file1:        { label: Datei 1 }
        file1name:    { label: Name Datei 1 }
        file2:        { label: Datei 2 }
        file2name:    { label: Name Datei 2 }
        file3:        { label: Datei 3 }
        file3name:    { label: Name Datei 3 }
        file4:        { label: Datei 4 }
        file4name:    { label: Name Datei 4 }
        link1:        { label: Link 1 }
        link1name:    { label: Name Link 1 }
        link2:        { label: Link 2 }
        link2name:    { label: Name Link 2 }
        is_published: { label: Publiziert? }
      list:    
        title: Projekte
        layout:  stacked
        display: [title, description]
        max_per_page: 10
        batch_actions: {}
        object_actions:
          _edit: { label: "Editieren" }
          _delete: { label: "Löschen" }
        actions:
          _new: { label: "Neu" }
        params:  |
          <h2>%%is_published%% %%title%%</h2><br/>
          <table style="border-style:none" cellpadding="0" cellspacing="0" border="0"><tr style="border-style:none"><td width="100%" style="border-style:none">
          <table style="border-style:none" cellpadding="0" cellspacing="0" border="0"><tbody style="border-style:none; padding: 0px"><tr style="border-style:none; padding: 0px"><td class="name" style="border-style:none; padding: 0px">Beschreibung:</td><td class="value" style="border-style:none">
          %%description%%</td></tr></tbody></table>
          </td><td style="border-style:none"><img src="/uploads/project/images/thumb_%%image%%" /></td></tr></table>
      filter:
        display: [title, description, is_published]
      form:
        class:   AdminSyrinxProjectForm
      edit:
        title: Projekt "%%title%%" editieren
        actions:
          _delete: { label: Projekt löschen }
          _list: { label: "Zurück zur Liste" }
          _save: { label: "Speichern" }
      new:
        title: Projekt erstellen
        actions:
          _list: { label: "Zurück zur Liste" }
          _save: { label: "Speichern" }
