<?php

/**
 * SyrinxCalendarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SyrinxCalendarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SyrinxCalendarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SyrinxCalendar');
    }
}