<?php

/**
 * SyrinxProjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SyrinxProjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SyrinxProjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SyrinxProject');
    }
}