<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/07 21:01:41

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=62.112.152.161;port=3306;dbname=usr_web161_1',
  'username' => 'web161',
  'password' => 'panflute',
  'name' => 'doctrine',
)),);
