# src/OG/InversaBundle/Resources/config/doctrine/AgendaItem.orm.yml
OG\InversaBundle\Entity\AgendaItem:
    type: entity
    table: agendaitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
            nullable: true
        eventdate:
            type: datetime
        eventtime:
            type: string
            length: 50
            nullable: true
        participants:
            type: string
            length: 1024
            nullable: true
        isactive:
            type: boolean
            nullable: true
    oneToMany:
        documents:
            targetEntity: Document
            mappedBy: agendaitem
        images:
            targetEntity: Image
            mappedBy: agendaitem
        links:
            targetEntity: WebUrl
            mappedBy: agendaitem
    manyToOne:
        location:
            targetEntity: Location
            joinColumn:
                name: location_id
                referencedColumnName: id