# src/OG/InversaBundle/Resources/config/doctrine/AgendaItem.orm.yml
OG\InversaBundle\Entity\AgendaItem:
    type: entity
    table: agendaitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text