# src/OG/InversaBundle/Resources/config/doctrine/Image.orm.yml
OG\InversaBundle\Entity\Image:
    type: entity
    table: image
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        doctype:
            type: string
            length: 8
            nullable: true  
        path:
            type: string
            length: 255      
    manyToOne:
        agendaitem:
            targetEntity: AgendaItem
            inversedBy: images
            joinColumn:
                name: agendaitem_id
                referencedColumnName: id
        projectitem:
            targetEntity: ProjectItem
            inversedBy: images
            joinColumn:
                name: projectitem_id
                referencedColumnName: id
        pressitem:
            targetEntity: PressItem
            inversedBy: images
            joinColumn:
                name: pressitem_id
                referencedColumnName: id
        galleryitem:
            targetEntity: GalleryItem
            inversedBy: images
            joinColumn:
                name: galleryitem_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]