# src/OG/InversaBundle/Resources/config/doctrine/InversaUser.orm.yml
OG\InversaBundle\Entity\InversaUser:
    type: entity
    table: inversauser
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 32
            unique: true
        salt:
            type: string
            length: 32            
        name:
            type: string
            length: 255
            nullable: true
        firstname:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 60
            nullable: true
        password:
            type: string
            length: 40
        lastlogin:
            type: datetime
            nullable: true
        isactive:
            type: boolean
            nullable: true