# src/OG/InversaBundle/Resources/config/doctrine/MediaItem.orm.yml
OG\InversaBundle\Entity\MediaItem:
    type: entity
    table: mediaitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
            nullable: true
        doctype:
            type: string
            length: 8
            nullable: true  
        path:
            type: string
            length: 255                 
        isactive:
            type: boolean
            nullable: true
    oneToOne:
        image:
            targetEntity: Image
            joinColumn:
                name: image_id
                referencedColumnName: id
            cascade: [ "persist", "remove" ]            
    lifecycleCallbacks:
        prePersist: [preUpload]
        preUpdate: [preUpload]
        postPersist: [upload]
        postUpdate: [upload]
        postRemove: [removeUpload]            
