# src/OG/InversaBundle/Resources/config/doctrine/PressItem.orm.yml
OG\InversaBundle\Entity\PressItem:
    type: entity
    table: pressitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
            nullable: true
        published:
            type: datetime
        isactive:
            type: boolean
    oneToMany:
        documents:
            targetEntity: Document
            mappedBy: pressitem
        images:
            targetEntity: Image
            mappedBy: pressitem
        links:
            targetEntity: WebUrl
            mappedBy: pressitem