# src/OG/InversaBundle/Resources/config/doctrine/ProjectItem.orm.yml
OG\InversaBundle\Entity\ProjectItem:
    type: entity
    table: projectitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:        
            type: text
            nullable: true
        day:
            type: datetime
            nullable: true
        location:
            type: text
            nullable: true
        isactive:
            type: boolean
            nullable: true
    oneToMany:
        documents:
            targetEntity: Document
            mappedBy: projectitem
            cascade: ["persist", "remove"]
        images:
            targetEntity: Image
            mappedBy: projectitem
            cascade: ["persist", "remove"]
        links:
            targetEntity: WebUrl
            mappedBy: projectitem
            cascade: ["persist", "remove"]