# src/OG/InversaBundle/Resources/config/doctrine/ProjectItem.orm.yml
OG\InversaBundle\Entity\ProjectItem:
    type: entity
    table: projectitem
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        description:
            type: text
            nullable: true
        isactive:
            type: boolean
            nullable: true
    oneToMany:
        documents:
            targetEntity: Document
            mappedBy: projectitem
        images:
            targetEntity: Image
            mappedBy: projectitem
        links:
            targetEntity: WebUrl
            mappedBy: projectitem