# src/OG/InversaBundle/Resources/config/doctrine/WebUrl.orm.yml
OG\InversaBundle\Entity\WebUrl:
    type: entity
    table: weburl
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        url:
            type: string
            length: 1024
    manyToOne:
        agendaitem:
            targetEntity: AgendaItem
            inversedBy: links
            joinColumn:
                name: agendaitem_id
                referencedColumnName: id
        projectitem:
            targetEntity: ProjectItem
            inversedBy: links
            joinColumn:
                name: projectitem_id
                referencedColumnName: id
        pressitem:
            targetEntity: PressItem
            inversedBy: links
            joinColumn:
                name: pressitem_id
                referencedColumnName: id